### PR TITLE
[dom-mc] ParaView with Mesa

### PR DESCRIPTION
**Pull request by lucamar**
Draft recipe of `ParaView 5.7.0` with `CrayGNU-20.06` and `Mesa`. The build fails with the error:
```
[ 11%] Building CXX object VTK/Wrapping/PythonCore/CMakeFiles/WrappingPythonCore.dir/P
yVTKMethodDescriptor.cxx.o
cd /run/user/21827/easybuild/build/ParaView/5.7.0/CrayGNU-20.06-OSMesa-python3/easybui
ld_obj/VTK/Wrapping/PythonCore && /opt/cray/pe/craype/2.6.5/bin/CC  -DWrappingPythonCo
re_EXPORTS -I/run/user/21827/easybuild/build/ParaView/5.7.0/CrayGNU-20.06-OSMesa-pytho
n3/easybuild_obj/VTK/Wrapping/PythonCore -I/run/user/21827/easybuild/build/ParaView/5.
7.0/CrayGNU-20.06-OSMesa-python3/ParaView-v5.7.0/VTK/Wrapping/PythonCore -I/run/user/2
1827/easybuild/build/ParaView/5.7.0/CrayGNU-20.06-OSMesa-python3/easybuild_obj/VTK/Com
mon/Core -I/run/user/21827/easybuild/build/ParaView/5.7.0/CrayGNU-20.06-OSMesa-python3
/ParaView-v5.7.0/VTK/Common/Core -I/run/user/21827/easybuild/build/ParaView/5.7.0/Cray
GNU-20.06-OSMesa-python3/easybuild_obj/VTK/Utilities/Python -I/run/user/21827/easybuil
d/build/ParaView/5.7.0/CrayGNU-20.06-OSMesa-python3/ParaView-v5.7.0/VTK/Utilities/Pyth
on -isystem /run/user/21827/easybuild/build/ParaView/5.7.0/CrayGNU-20.06-OSMesa-python
3/easybuild_obj/VTK/Utilities/KWIML -isystem /run/user/21827/easybuild/build/ParaView/
5.7.0/CrayGNU-20.06-OSMesa-python3/ParaView-v5.7.0/VTK/Utilities/KWIML -isystem /run/u
ser/21827/easybuild/build/ParaView/5.7.0/CrayGNU-20.06-OSMesa-python3/easybuild_obj/VT
K/Utilities/KWSys -isystem /run/user/21827/easybuild/build/ParaView/5.7.0/CrayGNU-20.0
6-OSMesa-python3/ParaView-v5.7.0/VTK/Utilities/KWSys -isystem /opt/intel/compilers_and
_libraries/linux/tbb/include -isystem /opt/python/3.8.2.1/include/python3.8  -O2 -fno-
math-errno -fPIC  -O2 -g -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidde
n   -std=c++11 -o CMakeFiles/WrappingPythonCore.dir/PyVTKMethodDescriptor.cxx.o -c /ru
n/user/21827/easybuild/build/ParaView/5.7.0/CrayGNU-20.06-OSMesa-python3/ParaView-v5.7.0/VTK/Wrapping/PythonCore/PyVTKMethodDescriptor.cxx
/run/user/21827/easybuild/build/ParaView/5.7.0/CrayGNU-20.06-OSMesa-python3/ParaView-v5.7.0/VTK/Wrapping/PythonCore/PyVTKMethodDescriptor.cxx:230:1: error: cannot convert 'std::nullptr_t' to 'Py_ssize_t' {aka 'long int'} in initialization
 };
 ^
make[2]: *** [VTK/Wrapping/PythonCore/CMakeFiles/WrappingPythonCore.dir/build.make:92: VTK/Wrapping/PythonCore/CMakeFiles/WrappingPythonCore.dir/PyVTKMethodDescriptor.cxx.o] Error 1
```
Any advice to address the issue is welcome.

### CODE REVIEW

**Comment by henrique** [comment]
There's a compilation problem with the py3.8 header:
/tmp/jenscscs/80c62dbmc/ParaView/5.7.0/CrayGNU-20.06-OSMesa-python3/ParaView-v5.7.0/VTK/Wrapping/PythonCore/PyVTKMethodDescriptor.cxx:230:1: error: cannot convert 'std::nullptr_t' to 'Py_ssize_t' {aka 'long int'} in initialization

**Comment by henrique** [comment]
There was a bug report in ParaView 5.6 here: https://bugzilla.redhat.com/show_bug.cgi?id=1743896

**Comment by lucamar** [comment]
Thanks for your comment @henrique: we have the newer `Paraview 5.8.0` with `EGL` installed on the gpu nodes, I might try with that version. I don't know if there are conflicts with the `Mesa` dependencies, though.

**Comment by henrique** [comment]
> Thanks for your comment @henrique: we have the newer `Paraview 5.8.0` with `EGL` installed on the gpu nodes, I might try with that version. I don't know if there are conflicts with the `Mesa` dependencies, though.

nice thx, if that doesn't work perhaps it's possible to compile with the system py3.6 (?)

**Comment by lucamar** [comment]
If the build with `ParaView 5.8.0` fails as well, I will configure the build using the system `python3`, as suggested by @henrique, as follows: 
```
-DPYTHON_EXECUTABLE=/usr/bin/python3
```

The version of the system python should not raise the issue:
```
$ /usr/bin/python3 --version
Python 3.6.10
```
